version: '3.8'

services:
  mongodb:
    image: femoliv/mongodb:v2
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  nodejs:
    image: femoliv/nodejs:v2
    container_name: nodejs
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/meu_banco_dados
    depends_on:
      - mongodb # dependência no serviço mongodb
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
    driver: local
