# usa a imagem oficial do mongodb como base - versão mais recente
FROM mongo:latest

# define o diretório de trabalho dentro do contêiner
WORKDIR /mongodb

# exponha a porta padrão do mongodb (padrão)
EXPOSE 27017